<script>
  import TextCode from './TextCode.svelte'
  import { page } from '$app/stores'
  import { fly } from 'svelte/transition'

  import Icon from '@iconify/svelte/dist/OfflineIcon.svelte'
  import { QR } from '$icons'
  import { QRCode } from '$icons'
  import { Share } from '$icons'
  import { Floppy } from '$icons'

  import { Transfer } from '$icons'
  import { Mobile } from '$icons'
  import { Desktop } from '$icons'

  import { Error } from '$icons'

  const handlescan = e => window.location = `/drop/${e.detail.code}`

  let err, errtimeout
</script>

<section>
  <h1>
    <Icon inline={true} icon={QR} class='fill-current -ml-4 md:-ml-6 mr-2' />
    Import a save
  </h1>

  <p>
    Enter the ShareScreen code or scan the QR code on your Mobile device to transfer the save data .
  </p>

  <div class='text-4xl inline-flex items-center transform scale-75 md:scale-100 -ml-4 md:my-0'>
    <Icon inline={true} height=0.9em icon={Mobile} class=fill-current />
    <Icon inline={true} height=0.6em icon={Transfer} class='fill-current mr-2 ml-1' />
    <Icon inline={true} icon={Desktop} class=fill-current />
  </div>

  <TextCode
    on:code={handlescan}
  />

  <ol>
    <li>Open your <a href='/saves'><mark>Save files <Icon inline={true} height=0.9em icon={Floppy} class=fill-current /></mark></a> on your first device</li>
    <li>Select the <mark>Share <Icon inline={true} icon={Share} class='fill-current' /></mark> icon on the save you want to transfer</li>
    <li>Open <mark>this page</mark> on your second device</li>
    <li>Enter the <mark>Code</mark> or scan the <mark>QR code <Icon inline={true} icon={QRCode} class='fill-current' /></mark> with your camera</li>
  </ol>

  <i class='text-xs text-gray-500 leading-3 max-w-xs text-center'>
    This will open a tinyurl link and redirect you back to the site.
    Make sure to only scan QR codes generated by https://nuzlocke.app
  </i>

</section>

<style lang="postcss">
  h1 { @apply text-2xl md:text-4xl font-bold inline-flex items-center -mb-2 }
  p{ @apply text-center leading-5 text-sm max-w-md }
  ol { @apply text-sm leading-4 list-outside list-decimal }
  li { @apply mb-2 md:mb-1 md:pl-2 md:-ml-2 }
  mark { @apply inline-flex items-center transition gap-x-1 bg-yellow-200 leading-5 font-bold px-1 mx-px }
  a mark:hover { @apply bg-yellow-400 cursor-pointer }

  section {
    @apply bg-gray-50 text-gray-800 rounded-xl py-10 px-6 md:px-12 overflow-hidden flex flex-col items-center mx-auto gap-y-4
  }

  :global(.dark) section {
    @apply bg-gray-800 text-white
  }
</style>
