<script>
  import QRScanner from './QRScanner.svelte'

  import { page } from '$app/stores'
  import { fly } from 'svelte/transition'

  import Icon from 'svelte-icons-pack'
  import QR from 'svelte-icons-pack/cg/CgQr'
  import QRCode from 'svelte-icons-pack/ri/RiDeviceQrCodeLine'
  import Share from 'svelte-icons-pack/ri/RiSystemShareForwardLine'
  import Floppy from 'svelte-icons-pack/im/ImFloppyDisk'

  import Transfer from 'svelte-icons-pack/bi/BiTransfer'
  import Mobile from 'svelte-icons-pack/im/ImMobile2'
  import Desktop from 'svelte-icons-pack/io/IoDesktopSharp'

  import Error from 'svelte-icons-pack/bi/BiErrorAlt'

  const fixIcon = i => ({ ...i, c: i.c.replace(/fill="#000000"/g, '') })

  const FloppyIcon = fixIcon(Floppy)
  const MobileIcon = fixIcon(Mobile)

  const handlescan = e => {
    const url = e.detail.value
    console.log('url', url, e)

    if (!url.startsWith(`${window.location.protocol}//${$page.host}/`))
      return handleerror(`Invalid QR code link - Only accept links to //${$page.host}/drop/...`)

    window.location = e.detail.value
  }

  let err, errtimeout
  const handleerror = e => {
    err = e
    clearTimeout(errtimeout)
    setTimeout(() => err = false, 1500)
  }

</script>

<section>
  <h1>
    <Icon src={QR} className='fill-current -ml-4 md:-ml-6 mr-2' />
    Import a save
  </h1>

  <p>
    Scan a QR code on your Mobile device using your camera to transfer the save data.
  </p>

  <div class='text-4xl inline-flex items-center transform scale-75 md:scale-100 -ml-4 md:my-4'>
    <Icon size=0.9em src={MobileIcon} className=fill-current />
    <Icon size=0.6em src={Transfer} className='fill-current mr-2 ml-1' />
    <Icon src={Desktop} className=fill-current />
  </div>

  <ol>
    <li>Open your <a href='/saves'><mark>Save files <Icon size=0.9em src={FloppyIcon} className=fill-current /></mark></a> on your first device</li>
    <li>Select the <mark>Share <Icon src={Share} className='fill-current' /></mark> icon on the save you want to transfer</li>
    <li>Open <a href='/transfer'><mark>this page</mark></a> on your second device</li>
    <li>Scan the <mark>QR code <Icon src={QRCode} className='fill-current' /></mark> with your camera</li>
  </ol>

  <div class='rounded-xl overflow-hidden max-w-sm'>
    <QRScanner
      on:scan={handlescan}
      on:error={handleerror}
      />
  </div>

  <i class='text-xs text-gray-500 leading-3 max-w-xs text-center'>
    This will open a tinyurl link and redirect you back to the site.
    Make sure to only scan QR codes generated by https://nuzlocke.vercel.app
  </i>

</section>


{#if err}
  <div
    transition:fly={{ y: 50 }}
    class='fixed bottom-0 left-0 md:left-1/2 md:-translate-x-1/2 px-4 w-full md:w-auto z-50' >
    <div class='flex flex-col items-center text-center z-50 max-w-base px-6 justify-center text-red-600 bg-red-100 rounded-t-lg py-2 w-full text-sm'>
      <span class='inline-flex items-center'>
        <Icon src={Error} size=1.8em className='mr-2 fill-current' />
        <b>Something went wrong</b>
      </span>
      {err}
    </div>
  </div>
{/if}


<style>
  h1 { @apply text-2xl md:text-4xl font-bold inline-flex items-center -mb-2 }
  p{ @apply text-center leading-5 text-sm max-w-xs }
  ol { @apply text-sm leading-4 list-outside list-decimal }
  li { @apply mb-2 md:mb-1 md:pl-2 md:-ml-2 }
  mark { @apply inline-flex items-center transition gap-x-1 bg-yellow-200 leading-5 font-bold px-1 mx-px }
  a mark:hover { @apply bg-yellow-400 cursor-pointer }

  section {
    @apply bg-gray-50 text-gray-800 rounded-xl py-10 px-6 md:px-12 overflow-hidden flex flex-col items-center mx-auto gap-y-4
  }

  :global(.dark) section {
    @apply bg-gray-800 text-white
  }


</style>
